# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: School Programs
email: fidzlieazriel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Our journey began with the realization that creating textual content on the web to learn programming is not enough.
  We recognize that most online tutorials, including our own, can appear as confusing walls of text, which can be a significant hurdle to learning.
twitter_username: mas.ulee
github_username: Julius-Ulee
minimal_mistakes_skin: dirt
comments:
  provider: "disqus"
  disqus:
    shortname: "julius-ulee-github-io"
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: OFEPETCMLI
  index_name: School-Programs
  search_only_api_key: 52e3d4326b143f0770b48aaa0a2e4ff5
  powered_by: false
logo: "/assets/images/favicon.ico"
url: "https://schoolprograms.my.id"
baseurl: ""
repository: "Julius-Ulee/School-Programs"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/jakarta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

google_site_verification : "4892blZfABQVhd6ccFz_dAVuV5q2Y2YQRUgNE2Ux7_I"

include:
  - _pages

collections:
  algoritma:
    output: true
    permalink: /:collection/:path/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "School Programs"
  avatar : "/assets/images/stationery.png"
  bio    : "Kami pengembang teknologi yang berkomitmen meretas masa depan melalui inovasi teknologi untuk solusi tantangan global. Kami siap memimpin perubahan melalui riset, pengembangan, dan implementasi teknologi terdepan."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:fidzlieazriel@email.com"
   # - label: "Website"
   #   icon: "fas fa-fw fa-link"
   #   url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Julius-Ulee"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mas.ulee"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Julius-Ulee"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mas.ulee"
    - label: "Status"
      icon: "fa fa-signal"
      url: "https://status.schoolprograms.my.id/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
  # _algoritma
  - scope:
      path: ""
      type: algoritma
    values:
      sidebar:
        nav: "algoritma"
      layout: single
      author_profile: true
      comments: true
      share: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
